### PR TITLE
allow multiple dots in domain part

### LINKED ISSUE #2: Email addresses with more than 2 domainParts fail to parse
True, as expected:
```Elm
Email.isValid "user@one.two"
```

False, but I expected this to be valid:
```Elm
Email.isValid "user@one.two.three"
```

### PR DESCRIPTION
**Pull request by panthershark**
Closes #2

### CODE REVIEW

**Review by skyqrose — APPROVED** [review]
Yeah, this is an improvement.

Email addresses are complicated, though, and it's probably worth going through the spec or other languages' implementations of email validation. It's easy to make assumptions about email address formats, but there are a lot of surprisingly valid email addresses.

Here's a description of some surprising things that are allowed by the standard, along with a bunch of test cases. https://haacked.com/archive/2007/08/21/i-knew-how-to-validate-an-email-address-until-i.aspx/ (sorry for the swearing).

Here's another more straightforward description of valid email addresses: https://www.mailboxvalidator.com/resources/articles/acceptable-email-address-syntax-rfc/ (though it slightly contradicts the other link in some places)

It looks like your implementation is mostly consistent with those two, but there might be some more edge cases to check, or some extra punctuation that's allowed.

Email validation is hard, which is why it's important to have a package that takes care of all these nitty gritty details. Thanks for taking it on.

**Comment by michaeljones** [comment]
I like the idea of learning a bit more about parsers and having a well tested robust email parser seems like a great contribution to the community. @panthershark would you be happy if I tried to contribute to this project? I can't promise much but I can try. Mostly along the lines of adding more test cases and trying to work through them. 

Also do you have specific aims for the project? I guess in terms of speed versus good error messages? Not that I know much about speed but I am curious how you're thinking about it.

**Comment by michaeljones** [comment]
I've also come across: https://blogs.msdn.microsoft.com/testing123/2009/02/06/email-address-test-cases/

And: https://en.wikipedia.org/wiki/Email_address#Examples

**Comment by panthershark** [comment]
@michaeljones - I'd love contributions. Getting more test cases into the test suite would be a great start. If we can setup fuzzers in a reasonable way, that would be the next phase of testing.

Accuracy, reliability, and good error messages are top priorities for me.

**Pull request merged**
